name: AutoPkg Action
author: joncrain
description: GitHub Action to verify AutoPkg Recipes.

branding:
  icon: command
  color: gray-dark

inputs:
  autopkg_version:
    default: https://github.com/autopkg/autopkg/releases/download/v2.3.1/autopkg-2.3.1.pkg
    required: false

runs:
  using: "composite"
  steps:
    - id: autopkg_check
      run: |
        curl -L ${{ inputs.autopkg_version }} --output /tmp/autopkg.pkg
        sudo installer -pkg /tmp/autopkg.pkg -target /
        defaults write com.github.autopkg RECIPE_REPO_DIR "$(pwd)"
        defaults write com.github.autopkg FAIL_RECIPES_WITHOUT_TRUST_INFO -bool NO
        find ./ -type f -name "*.recipe" -exec bash -c 'autopkg run '{} \;
      shell: bash
